# Generated by Django 5.2.17 on 2026-09-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sport', models.CharField(choices=[('VOLLEYBALL', 'Volleyball'), ('BASKETBALL', 'Basketball'), ('SOCCER', 'Soccer')], max_length=20)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('DELUXE', 'Deluxe')], max_length=20)),
                ('hour_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
