# Generated by Django 5.2.17 on 2026-09-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_court'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='court',
            constraint=models.CheckConstraint(condition=models.Q(('hour_price__gt', 0)), name='court_hour_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.CheckConstraint(condition=models.Q(('sport__in', ['VOLLEYBALL', 'BASKETBALL', 'SOCCER'])), name='court_sport_valid'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', ['BASIC', 'PREMIUM', 'DELUXE'])), name='court_tier_valid'),
        ),
    ]
