# Generated by Django 5.2.17 on 2026-09-11 23:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_court_court_hour_price_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
