# Generated by Django 5.2.17 on 2026-09-11 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_court_hour_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.court')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='booking_starts_before_ends'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'CANCELLED'])), name='booking_status_valid'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('court', 'starts_at'), name='unique_booking_per_court_time')],
            },
        ),
    ]
