# Generated by Django 5.2.17 on 2026-09-17 00:02

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at', models.Func(models.F('starts_at'), function='DATE_TRUNC', output_field=models.DateTimeField(), template="DATE_TRUNC('hour', %(expressions)s)"))), name='booking_starts_at_full_hour'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at', django.db.models.expressions.CombinedExpression(models.F('starts_at'), '+', models.Value(datetime.timedelta(seconds=3600))))), name='booking_slot_lasts_one_hour'),
        ),
    ]
