# Generated by Django 5.2.17 on 2026-10-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kind',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'CUSTOMER'), ('reason__exact', ''), ('user__isnull', False)), models.Q(('kind', 'MAINTENANCE'), ('user__isnull', True), models.Q(('reason__exact', ''), _negated=True)), _connector='OR'), name='booking_kind_matches_user_and_reason'),
        ),
    ]
