# Generated by Django 5.2.17 on 2026-10-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
